# Site settings
exclude: [README.md]
title: Wilker Aziz
email: wilker.aziz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Here you will find details about my work.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wilkeraziz.github.io/dcs-site/index.html" # the base hostname & protocol for your site
twitter_username: wilkeraziz
github_username:  wilkeraziz
paginate: 3

# CV
cv: "cv/cv.pdf"

# current department
current_department: ILLC
departamental_page: http://wilkeraziz.github.io/dcs-site
current_dpt_email: w.aziz@uva.nl

# useful links
poesia: http://poesiaehcoisadepoeta.blogspot.com
google_scholar_url: http://scholar.google.co.uk/citations?user=phgBJXYAAAAJ&hl=en
dcs_page: http://wilkeraziz.github.io/dcs-site
modist_url: http://staffwww.dcs.shef.ac.uk/people/L.Specia/projects/modist.html
lucia_specia: http://staffwww.dcs.shef.ac.uk/people/L.Specia
khalil_simaan: https://staff.fnwi.uva.nl/k.simaan/
slpll_url: https://staff.fnwi.uva.nl/k.simaan/research_all.html
uva_url: http://www.illc.uva.nl/

# Build settings
markdown: kramdown

# Paper entries

papers:
    -
        layout: paper
        paper-type: inproceedings
        selected: y
        year: 2014
        img: emnlp2014
        title: Exact Decoding for Phrase-Based Statistical Machine Translation
        authors: Wilker Aziz, Marc Dymetman and Lucia Specia
        booktitle: Proceedings of EMNLP
        doc-url: http://www.aclweb.org/anthology/D/D14/D14-1131.pdf
        booktitle-url: http://emnlp2014.org
        #code: https://github.com/wilkeraziz/chisel
        venue: conference
        abstract: >
            The combinatorial space of translation derivations in phrase-based statistical machine translation is given by the intersection between a translation lattice and a target language model. 
            We replace this intractable intersection by a tractable relaxation which incorporates a low-order upperbound on the language model. 
            Exact optimisation is achieved through a coarse-to-fine strategy with connections to adaptive rejection sampling. 
            We perform exact optimisation with unpruned language models of order 3 to 5 and show search-error curves for beam search and cube pruning on standard test sets. 
            This is the first work to tractably tackle exact optimisation with language models of orders higher than 3.
        errata: >
            In the introduction, we comment about works that propose some form of exact search. In some cases, authors have proposed algorithms whose applicability seems mostly limited to toy models, such as Aziz et al. (2013). In other cases, authors modified the model in different (non-obvious) ways (e.g. monotone translation, compact rule sets, lower-order LM, entropy pruning for LM) enabling exact search. We mistakenly listed Iglesias et al (2009) amongst the former group. A more accurate wording would be:
            <p>
            <blockquote>
            To date, most attempts were limited to short sentences and/or somewhat toy models trained with artificially small datasets (Germann et al., 2001; Aziz et al., 2013). Other work has employed less common approximations to the model reducing its search space complexity (Kumar et al., 2006; Iglesias et al., 2009; Chang and Collins, 2011; Rush and Collins, 2011).
            </blockquote>
            <p><br/>Thanks to Gonzalo Iglesias for kindly warning me about this problem.
        bibtex: >
            @InProceedings{aziz-dymetman-specia:2014:EMNLP2014,
              author    = {Aziz, Wilker  and  Dymetman, Marc  and  Specia, Lucia},
              title     = {Exact Decoding for Phrase-Based Statistical Machine Translation},
              booktitle = {Proceedings of the 2014 Conference on Empirical Methods in Natural Language Processing (EMNLP)},
              month     = {October},
              year      = {2014},
              address   = {Doha, Qatar},
              publisher = {Association for Computational Linguistics},
              pages     = {1237--1249},
              url       = {http://www.aclweb.org/anthology/D14-1131}
            }
    -
        layout: paper
        paper-type: inproceedings
        selected: y
        year: 2013
        img: wmt2013
        title: Investigations in Exact Inference for Hierarchical Translation
        authors: Wilker Aziz, Marc Dymetman and Sriram Venkatapathy
        booktitle: Proceedings of the WMT
        doc-url: http://www.aclweb.org/anthology/W/W13/W13-2260.pdf
        booktitle-url: http://www.statmt.org/wmt13/
        #code: https://github.com/wilkeraziz/chisel
        venue: conference
        abstract: >
            We present a method for inference in hierarchical phrase-based translation, where both optimisation and sampling are performed in a common exact inference framework related to adaptive rejection sampling. 
            We also present a first implementation of that method along with experimental results shedding light on some fundamental issues. 
            In hierarchical translation, inference needs to be performed over a high-complexity distribution defined by the intersection of a translation hypergraph and a target language model. 
            We replace this intractable distribution by a sequence of tractable upperbounds for which exact optimisers and samplers are easy to obtain. 
            Our experiments show that exact inference is then feasible using only a fraction of the time and space that would be required by the full intersection, without recourse to pruning techniques that only provide approximate solutions. 
            While the current implementation is limited in the size of inputs it can handle in reasonable time, our experiments provide insights towards obtaining future speedups, while staying in the same general framework.
        bibtex: >
            @InProceedings{aziz-dymetman-venkatapathy:2013:WMT,
              author    = {Aziz, Wilker  and  Dymetman, Marc  and  Venkatapathy, Sriram},
              title     = {Investigations in Exact Inference for Hierarchical Translation},
              booktitle = {Proceedings of the Eighth Workshop on Statistical Machine Translation},
              month     = {August},
              year      = {2013},
              address   = {Sofia, Bulgaria},
              publisher = {Association for Computational Linguistics},
              pages     = {472--483},
              url       = {http://www.aclweb.org/anthology/W13-2260}
            }
    -
        layout: paper
        paper-type: inproceedings
        selected: y
        year: 2013
        img: conll2013
        title: Multilingual WSD-like Constraints for Paraphrase Extraction
        authors: Wilker Aziz and Lucia Specia
        booktitle: Proceedings of the Seventeenth Conference on Computational Natural Language Learning (CoNLL)
        doc-url: http://www.aclweb.org/anthology/W/W13/W13-3522.pdf
        booktitle-url: http://www.clips.uantwerpen.be/conll2013/
        #code: https://github.com/wilkeraziz/chisel
        venue: conference
        abstract: >
            The use of pivot languages and word-alignment techniques over bilingual corpora has proved an effective approach for extracting paraphrases of words and short phrases. However, inherent ambiguities in the pivot language(s) can lead to inadequate paraphrases. 
            We propose a novel approach that is able to extract paraphrases by pivoting through multiple languages while discriminating word senses in the input language, i.e., the language to be paraphrased. Text in the input language is annotated with "senses" in the form of foreign phrases obtained from bilingual parallel data and automatic word-alignment. This approach shows 62% relative improvement over previous work in generating paraphrases that are judged both more accurate and more fluent.
        bibtex: >
            @InProceedings{aziz-specia:2013:CoNLL-2013,
              author    = {Aziz, Wilker  and  Specia, Lucia},
              title     = {Multilingual WSD-like Constraints for Paraphrase Extraction},
              booktitle = {Proceedings of the Seventeenth Conference on Computational Natural Language Learning},
              month     = {August},
              year      = {2013},
              address   = {Sofia, Bulgaria},
              publisher = {Association for Computational Linguistics},
              pages     = {202--211},
              url       = {http://www.aclweb.org/anthology/W13-3522}
            }
